version: '3'

services:
  hive-metastore-db:
    image: postgres:13
    container_name: metastore_db
    environment:
      POSTGRES_DB: metastore_db
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive_password
    volumes:
      - metastore_db_data:/var/lib/postgresql/data
    networks:
      - data-network

  hive-metastore:
    build:
      context: .
      dockerfile: hive.Dockerfile
    container_name: hive_metastore
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      # ДОБАВЛЕНО: -Dhive.metastore.warehouse.dir=/user/hive/warehouse
      # Это заставляет Hive использовать нашу примонтированную папку
      SERVICE_OPTS: "-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://metastore_db:5432/metastore_db -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=hive_password -Dhive.metastore.warehouse.dir=/user/hive/warehouse"
    ports:
      - "9083:9083"
    volumes:
      - warehouse_data:/user/hive/warehouse
    depends_on:
      - hive-metastore-db
    networks:
      - data-network

  spark-master:
    build: .
    container_name: spark_master
    user: root  # <--- !!! ВАЖНО: Даем права root, чтобы писать в общую папку без ошибок
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./app:/app
      - ./data:/data
      - warehouse_data:/user/hive/warehouse
    networks:
      - data-network

  spark-worker:
    build: .
    container_name: spark_worker
    user: root  # <--- !!! ВАЖНО: Тоже даем права root
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_MEMORY=1G
    volumes:
      - ./app:/app
      - ./data:/data
      - warehouse_data:/user/hive/warehouse
    depends_on:
      - spark-master
    networks:
      - data-network

volumes:
  metastore_db_data:
  warehouse_data:

networks:
  data-network:
    driver: bridge