# 1. Базовый образ (Debian 12 Bookworm)
FROM python:3.10-slim-bookworm

# 2. Устанавливаем Java и утилиты
# apt-get сам скачает правильную версию под x64
RUN apt-get update && \
    apt-get install -y openjdk-17-jre-headless procps curl && \
    rm -rf /var/lib/apt/lists/*

# 3. Настройка переменных окружения
# ВНИМАНИЕ: Здесь путь жестко задан для архитектуры amd64 (стандартные ПК)
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV SPARK_VERSION=3.5.0
ENV HADOOP_VERSION=3
ENV SPARK_HOME=/opt/spark
ENV PATH=$PATH:$SPARK_HOME/bin

# 4. Скачиваем Spark
RUN curl -O https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
    tar -xhf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
    mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} /opt/spark && \
    rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz

# 5. Копируем requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 6. Рабочая директория
WORKDIR /app

# 7. Заглушка
CMD ["tail", "-f", "/dev/null"]